name: Android Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        cd androidApp
        ./gradlew build
        ./gradlew lint
        echo "Copy the following to a local HTML file and open in a browser"
        cat app/build/reports/lint-results.html

